/* تعريب — taarib.h
 *
 * The stable C ABI of the Taarib Arabic text engine (crates/taarib-jisr).
 *
 * GENERATED FILE — DO NOT EDIT BY HAND. cbindgen produces this header from the
 * Rust surface on every build; any change made here is destroyed by the next
 * one. Fix the Rust, regenerate, commit both.
 *
 * Every function returns an int32_t status: zero is success, every failure is
 * negative, and the failing thread's full diagnosis — permanent code, Arabic
 * sentence, English sentence, suggested next action — is retrievable through
 * the taarib_khata_* functions. Ownership is stated per function in its
 * comment: who allocates, who frees, and how long a returned pointer stays
 * valid. The same contract, in longer form, is docs/abi.md. */

#ifndef TAARIB_H
#define TAARIB_H

/* Generated with cbindgen:0.29.4 */

/* Generated by cbindgen from taarib-jisr. Do not hand-edit; regenerate instead. */

#include <stdint.h>
#include <stddef.h>

/*
 [`TaaribHarf::alam`]: this glyph is a combining mark, positioned onto a base
 rather than advancing the pen.
 */
#define TAARIB_HARF_ALAMA (1 << 0)

/*
 [`TaaribSatr::alam`]: this is the last line of its paragraph, which is what
 stops justification stretching it across the full width.
 */
#define TAARIB_SATR_AKHIR (1 << 0)

/*
 [`TaaribSatr::alam`]: this line's base direction is right to left.
 */
#define TAARIB_SATR_YAMEEN (1 << 1)

/*
 [`TaaribKhiyarat::alam`]: this text is dialogue, which is what the
 keep-diacritics-in-dialogue policy keys on.
 */
#define TAARIB_KHIYAR_HIWAR (1 << 0)

/*
 [`TaaribKhiyarat::alam`]: the caller forbids wrapping entirely, as a
 single-line input field does.
 */
#define TAARIB_KHIYAR_SATR_WAHID (1 << 1)

/*
 [`TaaribMakhzanTakhtit::alam`]: the layout's overall direction is right to
 left.
 */
#define TAARIB_TAKHTIT_YAMEEN (1 << 0)

/*
 [`TaaribMakhzanTakhtit::alam`]: the overflow policy truncated the text.
 */
#define TAARIB_TAKHTIT_MAQSUS (1 << 1)

/*
 [`TaaribMakhzanTakhtit::alam`]: the text did not fit, and
 [`TaaribMakhzanTakhtit::tajawuz`] describes by how much.
 */
#define TAARIB_TAKHTIT_TAJAWUZ (1 << 2)

/*
 [`TaaribMakhzanTakhtit::alam`]: this layout came from the cache, so nothing
 was shaped.

 Exposed because an adapter's own diagnostics want the hit rate, and because a
 cache that never hits is a cache whose key is wrong.
 */
#define TAARIB_TAKHTIT_MAKHZAN (1 << 3)

/*
 [`TaaribNitaqUslub::alam`]: this span is italic or slanted.
 */
#define TAARIB_USLUB_MAAIL (1 << 0)

/*
 [`TaaribNitaqUslub::alam`]: this span is an opaque atom — a format
 placeholder or an inline sprite — and is never shaped.
 */
#define TAARIB_USLUB_DHARRA (1 << 1)

/*
 [`TaaribNitaqUslub::alam`]: this span sets a font index.
 */
#define TAARIB_USLUB_KHATT (1 << 2)

/*
 [`TaaribNitaqUslub::alam`]: this span sets a weight.
 */
#define TAARIB_USLUB_WAZN (1 << 3)

/*
 [`TaaribNitaqUslub::alam`]: this span sets a size.
 */
#define TAARIB_USLUB_HAJM (1 << 4)

/*
 [`TaaribNitaqUslub::alam`]: this span sets a colour.
 */
#define TAARIB_USLUB_LAWN (1 << 5)

/*
 The ABI's major version.

 Bumped when anything already shipped changes shape or meaning: a structure
 field moved, a status code repurposed, a contract reworded in a way an old
 caller would violate. A caller whose compiled-in major differs from the one
 [`taarib_abi_isdar`] reports must refuse to continue and say so in its own
 log; continuing past a major mismatch is undefined behaviour by definition,
 because the two sides no longer agree what the bytes between them mean.
 */
#define TAARIB_ABI_KABIR 1

/*
 The ABI's minor version.

 Bumped when something is appended — a new function, a new constant, a new
 structure. Everything an old caller compiled against keeps working, so a
 minor mismatch in either direction is not a reason to refuse; it is only a
 reason not to call what the running library does not have.
 */
#define TAARIB_ABI_SAGHEER 0

/*
 The operation succeeded.
 */
#define TAARIB_NAJAH 0

/*
 Something failed that no more specific code describes. The stashed [`Khata`]
 still names it exactly; this is the code, not the diagnosis.
 */
#define TAARIB_KHATA_AAM -1

/*
 A required pointer argument was null.
 */
#define TAARIB_MUASHIR_BATIL -2

/*
 A handle was not one this library issued, or was destroyed already.

 This is the use-after-free that generation tagging exists to catch. It is
 reported rather than executed, which is the difference between a bug report
 naming a stale handle and a crash dump in someone's game.
 */
#define TAARIB_MAQBAD_BATIL -3

/*
 The caller's buffer is too small. The required capacity has been written to
 the out-parameter and nothing else was written.

 Not an error in the usual sense — it is the negotiation the allocation-free
 hot path is built on. A caller grows once and retries, and from then on the
 buffer is big enough forever.
 */
#define TAARIB_SIAT_QASIRA -4

/*
 The caller was built against a different major version of this ABI.
 */
#define TAARIB_ISDAR_GHAYR_MUTAWAFIQ -5

/*
 A string argument was not valid UTF-8.
 */
#define TAARIB_TARMIZ_BATIL -6

/*
 A font was rejected, or could not be read.

 The stashed error names the missing table or feature, because "this font has
 no GSUB table and cannot join Arabic letters" is a sentence a user can act on
 and "font error" is not.
 */
#define TAARIB_KHATT_MARFUD -7

/*
 Shaping produced nothing for text that is not empty.
 */
#define TAARIB_TASHKEEL_FASHIL -8

/*
 An allocation failed. Reported rather than aborted: this library runs inside
 somebody else's process and does not get to decide that the process ends.
 */
#define TAARIB_DHAKIRA -9

/*
 An argument was structurally fine but its value is not usable — a negative
 width, a size of zero, a style span that points outside its text.
 */
#define TAARIB_QEEMA_BATILA -10

/*
 A panic was caught at the boundary and converted into a status.

 A panic unwinding into a game's C# or C++ frame would be a crash the player
 blames on the game. Every entry point catches, so this code means the library
 has a bug worth reporting — and the game is still running to report it.
 */
#define TAARIB_INHIYAR -11

/*
 The atlas is full and nothing in it may be evicted, because everything in it
 is referenced by the frame currently being drawn.
 */
#define TAARIB_LAWHA_MUMTALIA -12

/*
 The operation is not available in this build — a feature compiled out, or a
 platform that does not offer what was asked for.
 */
#define TAARIB_GHAYR_MADUM -13

/*
 The library has not been initialised, or was shut down.
 */
#define TAARIB_GHAYR_MUHAYYAA -14

/*
 The never-instantiated type behind [`TaaribKhatt`].
 */
typedef struct TaaribKhattKhas TaaribKhattKhas;

/*
 The never-instantiated type behind [`TaaribLawha`].
 */
typedef struct TaaribLawhaKhas TaaribLawhaKhas;

/*
 The never-instantiated type behind [`TaaribSilsila`].
 */
typedef struct TaaribSilsilaKhas TaaribSilsilaKhas;

/*
 The never-instantiated type behind [`TaaribSiyaq`].
 */
typedef struct TaaribSiyaqKhas TaaribSiyaqKhas;

/*
 How a context is built.
 */
typedef struct {
  /*
   The layout cache's budget in bytes. Zero disables the cache entirely,
   which is what an offline compiler wants and what a game never does.
   */
  size_t mizaniyat_makhzan;
  /*
   How many glyph buffers to keep pooled for the allocation-free path.
   */
  uint32_t adad_makhazin;
  /*
   Reserved, must be zero.
   */
  uint32_t hashw;
} TaaribKhiyaratSiyaq;

/*
 An engine context: the caches, the buffers, and the capture channel.

 Opaque and never dereferenced. The value is a generation-tagged index into
 this library's own table, carried in a pointer-shaped type so that C callers
 get type safety between handle kinds and so that a stale handle is detected
 by lookup rather than by touching freed memory. Vulkan's non-dispatchable
 handles work the same way and for the same reason.
 */
typedef TaaribSiyaqKhas *TaaribSiyaq;

/*
 A loaded, validated font.
 */
typedef TaaribKhattKhas *TaaribKhatt;

/*
 A font's metrics, scaled to a pixel size.
 */
typedef struct {
  /*
   How far the font rises above the baseline.
   */
  float suud;
  /*
   How far it falls below, as a positive number.
   */
  float hubut;
  /*
   The gap the font asks for between lines.
   */
  float fajwa;
  /*
   The line height the font recommends.
   */
  float irtifa_satr;
  /*
   Cap height.
   */
  float uluw_kabital;
  /*
   x-height.
   */
  float uluw_saghir;
  /*
   Units per em, as declared by the font.
   */
  uint32_t wahdat;
  /*
   Padding to a multiple of eight. Always written as zero; ignore it.
   */
  uint32_t hashw;
} TaaribQiyasatKhatt;

/*
 An ordered chain of fonts, tried in order per character.
 */
typedef TaaribSilsilaKhas *TaaribSilsila;

/*
 A style span over the caller's text.

 Only what changes layout is read. Colour is carried through untouched,
 because the engine does not draw — but it must survive reordering, or a
 coloured word inside a sentence loses its colour the moment the line is put
 into visual order.
 */
typedef struct {
  /*
   Byte offset of the span's first byte in the caller's text.
   */
  uint32_t bidaya;
  /*
   Length in bytes.
   */
  uint32_t tul;
  /*
   Colour as `0xRRGGBBAA`, read only when [`TAARIB_USLUB_LAWN`] is set.
   */
  uint32_t lawn;
  /*
   [`TAARIB_USLUB_MAAIL`] and the rest of the `TAARIB_USLUB_*` flags.
   */
  uint32_t alam;
  /*
   A size override in pixels, read only when [`TAARIB_USLUB_HAJM`] is set.
   */
  float hajm;
  /*
   Extra letter spacing for this span, in pixels.
   */
  float tabaud;
  /*
   A vertical offset from the baseline, in pixels.
   */
  float izaha;
  /*
   An atom's width in pixels, read only when [`TAARIB_USLUB_DHARRA`] is set.
   */
  float ard_dharra;
  /*
   An atom's height in pixels.
   */
  float irtifa_dharra;
  /*
   How far above the baseline an atom's bottom edge sits.
   */
  float asas_dharra;
  /*
   The caller's own reference to an atom, carried through untouched.
   */
  uint32_t marja_dharra;
  /*
   A variable-font weight, read only when [`TAARIB_USLUB_WAZN`] is set.
   */
  uint16_t wazn;
  /*
   Identifies this span in the output.
   */
  uint16_t id;
  /*
   The font index this span prefers, read only when [`TAARIB_USLUB_KHATT`]
   is set.
   */
  uint8_t khatt;
  /*
   Padding to a multiple of four. Always written as zero; ignore it.
   */
  uint8_t hashw[3];
} TaaribNitaqUslub;

/*
 An OpenType feature the caller wants on or off beyond the defaults.
 */
typedef struct {
  /*
   The four-character tag, for example `ss01`, in writing order.
   */
  uint8_t wasm[4];
  /*
   The value. Zero turns the feature off.
   */
  uint32_t qeema;
} TaaribSifa;

/*
 The decisions a caller makes once and records into a patch.
 */
typedef struct {
  /*
   Extra feature settings.
   */
  const TaaribSifa *sifat;
  /*
   How many.
   */
  size_t adad_sifat;
  /*
   How the base direction is decided: 0 automatic, 1 right to left,
   2 left to right.
   */
  uint32_t ittijah;
  /*
   The language: 0 detect, 1 Arabic, 2 Persian, 3 Urdu, 4 Latin.
   */
  uint32_t lugha;
  /*
   How surplus width is absorbed: 0 none, 1 spaces, 2 kashida,
   3 kashida then spaces.
   */
  uint32_t dabt;
  /*
   Where a line sits: 0 leading edge, 1 trailing edge, 2 centre, 3 filled.
   */
  uint32_t muhadhaha;
  /*
   Diacritics: 0 keep, 1 strip, 2 keep in dialogue only.
   */
  uint32_t tashkeel;
  /*
   Digits: 0 leave, 1 European, 2 Arabic-Indic, 3 Eastern Arabic-Indic.
   */
  uint32_t arqam;
  /*
   Overflow: 0 report, 1 shrink to fit, 2 truncate.
   */
  uint32_t tajawuz;
  /*
   The smallest size shrink-to-fit may use, in pixels.
   */
  float hajm_adna;
  /*
   Line height in pixels; zero or less means the font's own metrics decide.
   */
  float irtifa_satr;
  /*
   Extra spacing between every pair of glyphs, applied after shaping so it
   never disturbs joining.
   */
  float tabaud_ahruf;
  /*
   Extra spacing added to every space.
   */
  float tabaud_kalimat;
  /*
   [`TAARIB_KHIYAR_HIWAR`], [`TAARIB_KHIYAR_SATR_WAHID`].
   */
  uint32_t alam;
} TaaribKhiyarat;

/*
 One layout request.
 */
typedef struct {
  /*
   UTF-8 text in logical order, with markup and placeholders already lifted
   into spans. Not required to be NUL-terminated.
   */
  const uint8_t *nass;
  /*
   Its length in bytes.
   */
  size_t tul_nass;
  /*
   The style spans.
   */
  const TaaribNitaqUslub *nitaqat;
  /*
   How many.
   */
  size_t adad_nitaqat;
  /*
   The fonts to shape and draw with.
   */
  TaaribSilsila silsila;
  /*
   The size in pixels.
   */
  float hajm;
  /*
   The width available in pixels; zero or less means one line of whatever
   width the text needs.
   */
  float ard_mutah;
  /*
   The height available in pixels; zero or less means unbounded.
   */
  float irtifa_mutah;
  /*
   The decisions.
   */
  TaaribKhiyarat khiyarat;
} TaaribTalab;

/*
 One positioned glyph, ready to become two triangles.

 Twenty-four bytes, four-byte aligned, no padding. This is the structure a
 game process walks thousands of times per frame, so its size is a decision
 rather than an accident.

 Note what is absent: a codepoint. Nothing downstream of shaping is given the
 character a glyph came from, because a field that carried it would eventually
 be drawn from — which is the presentation-form pipeline this product exists
 to make impossible.
 */
typedef struct {
  /*
   The glyph identifier, in the font named by [`TaaribHarf::khatt`].
   */
  uint32_t muarrif;
  /*
   Byte offset into the caller's text of the cluster this glyph belongs to.
   */
  uint32_t anqud;
  /*
   Horizontal position of the glyph's origin, in pixels from the layout's
   left edge. Already in visual order.
   */
  float s;
  /*
   Vertical position of the origin, in pixels down from the layout's top.
   */
  float a;
  /*
   The advance this glyph contributed. Zero for marks.
   */
  float taqaddum;
  /*
   The style span this glyph inherited, so colour survives reordering.
   */
  uint16_t nitaq;
  /*
   Index into the font chain of the font this glyph belongs to.
   */
  uint8_t khatt;
  /*
   [`TAARIB_HARF_ALAMA`].
   */
  uint8_t alam;
} TaaribHarf;

/*
 One laid-out line.
 */
typedef struct {
  /*
   Index of this line's first glyph in the glyph buffer.
   */
  uint32_t awwal_harf;
  /*
   How many glyphs this line has.
   */
  uint32_t adad_huruf;
  /*
   First byte of the logical text this line covers.
   */
  uint32_t bidayat_mantiqi;
  /*
   One past the last byte.
   */
  uint32_t nihayat_mantiqi;
  /*
   The baseline's vertical position, in pixels from the layout's top.
   */
  float asas;
  /*
   Where the line box begins horizontally, after alignment.
   */
  float bidaya;
  /*
   The measured width of the line's content.
   */
  float ard;
  /*
   The line box's height.
   */
  float irtifa;
  /*
   How far the tallest content rises above the baseline.
   */
  float suud;
  /*
   How far the deepest content falls below it.
   */
  float hubut;
  /*
   How much width justification added to this line.
   */
  float dabt;
  /*
   [`TAARIB_SATR_AKHIR`], [`TAARIB_SATR_YAMEEN`].
   */
  uint32_t alam;
} TaaribSatr;

/*
 What overflowed, by how much.

 Not an error: a measurement the caller asked for. The patch compiler turns it
 into the overflow report, the review console sorts by it, and the workspace
 shows it beside the string as it is typed.
 */
typedef struct {
  /*
   The widest line's measured width, in pixels.
   */
  float ard;
  /*
   The width that was available.
   */
  float ard_mutah;
  /*
   The total height the text needed.
   */
  float irtifa;
  /*
   The height that was available, or zero when none was given.
   */
  float irtifa_mutah;
  /*
   The first line that exceeded the width.
   */
  uint32_t awwal_satr;
  /*
   How many lines exceeded it.
   */
  uint32_t adad_sutur;
} TaaribTaqreerTajawuz;

/*
 The caller-owned buffer the layout is written into.

 The caller owns both arrays and their lifetime; this library never allocates
 them, never frees them, and never keeps a pointer to them past the call. The
 `siaat_*` fields are capacity in elements and are read; the `adad_*` fields
 are how many were written and are written.

 When either array is too small, nothing is written, `adad_*` receives the
 required count for both arrays, and the call returns
 [`TAARIB_SIAT_QASIRA`](crate::khata_c::TAARIB_SIAT_QASIRA). A caller grows
 once and retries, and after the first few frames the buffer never grows
 again — which is what makes the hot path allocation-free in practice and not
 merely in principle.
 */
typedef struct {
  /*
   The caller's glyph array.
   */
  TaaribHarf *huruf;
  /*
   Its capacity, in elements.
   */
  size_t siaat_huruf;
  /*
   How many glyphs were written, or how many are required.
   */
  size_t adad_huruf;
  /*
   The caller's line array.
   */
  TaaribSatr *sutur;
  /*
   Its capacity, in elements.
   */
  size_t siaat_sutur;
  /*
   How many lines were written, or how many are required.
   */
  size_t adad_sutur;
  /*
   The width of the widest line.
   */
  float ard;
  /*
   The total height of every line box.
   */
  float irtifa;
  /*
   The size the text was finally laid out at, which differs from the size
   requested when the overflow policy shrank it to fit.
   */
  float hajm;
  /*
   [`TAARIB_TAKHTIT_YAMEEN`], [`TAARIB_TAKHTIT_MAQSUS`],
   [`TAARIB_TAKHTIT_TAJAWUZ`], [`TAARIB_TAKHTIT_MAKHZAN`].
   */
  uint32_t alam;
  /*
   Valid only when [`TAARIB_TAKHTIT_TAJAWUZ`] is set.
   */
  TaaribTaqreerTajawuz tajawuz;
} TaaribMakhzanTakhtit;

/*
 Text measured without positioning a single glyph.
 */
typedef struct {
  /*
   The width of the widest line.
   */
  float ard;
  /*
   The total height.
   */
  float irtifa;
  /*
   The first line's ascent.
   */
  float suud;
  /*
   The last line's descent.
   */
  float hubut;
  /*
   How many lines the text needed.
   */
  uint32_t adad_sutur;
  /*
   Padding to a multiple of eight. Always written as zero; ignore it.
   */
  uint32_t hashw;
} TaaribQiyasNass;

/*
 What the layout cache has been doing.

 Mirrors [`crate::khazina::IhsaatKhazina`] field for field. It is defined
 here rather than in `anwa.rs` only because it belongs to the cache, and the
 cache's surface — [`taarib_makhzan_ihsaat`] and this structure — was
 appended to the ABI as one piece; `anwa.rs` carries the frozen Phase 3 core
 and appending here keeps the append visible as an append. The layout rules
 are the same ones `anwa.rs` states: widest fields first, no implicit
 padding, nothing whose representation the compiler chooses.
 */
typedef struct {
  /*
   Layout requests served from the cache without shaping anything.
   */
  uint64_t isabat;
  /*
   Requests that had to be laid out in full.
   */
  uint64_t ikhfaqat;
  /*
   Layouts evicted to stay inside the byte budget.
   */
  uint64_t ikhlaat;
  /*
   What the cached layouts currently cost, in bytes.
   */
  uint64_t bayt;
  /*
   The byte budget the context was created with. Zero means the cache is
   disabled and every request shapes.
   */
  uint64_t mizaniya;
  /*
   How many layouts the cache holds right now.
   */
  uint32_t madkhalat;
  /*
   Padding to a multiple of eight. Always written as zero; ignore it.
   */
  uint32_t hashw;
} TaaribIhsaatKhazina;

/*
 A glyph atlas that grows and evicts at runtime.
 */
typedef TaaribLawhaKhas *TaaribLawha;

/*
 Everything that makes one rasterized image of a glyph distinct.
 */
typedef struct {
  /*
   The glyph identifier.
   */
  uint32_t muarrif;
  /*
   The pixel size in quarter-pixels.
   */
  uint16_t hajm_rubi;
  /*
   Index into the font chain.
   */
  uint8_t khatt;
  /*
   The subpixel bucket.
   */
  uint8_t bakat;
} TaaribMiftahShakl;

/*
 Where a glyph lives in the atlas, and how to draw it.
 */
typedef struct {
  /*
   The glyph's advance at this size.
   */
  float taqaddum;
  /*
   Left edge in the page, in pixels.
   */
  uint16_t s;
  /*
   Top edge in the page, in pixels.
   */
  uint16_t a;
  /*
   Width in pixels.
   */
  uint16_t ard;
  /*
   Height in pixels.
   */
  uint16_t irtifa;
  /*
   Left bearing: how far right of the pen the image starts.
   */
  int16_t izaha_s;
  /*
   Top bearing: how far above the baseline the image's top edge sits.
   */
  int16_t izaha_a;
  /*
   Which page.
   */
  uint16_t safha;
  /*
   Padding to a multiple of four. Always written as zero; ignore it.
   */
  uint16_t hashw;
} TaaribMawdiShakl;

/*
 One texture page, borrowed.

 `bayt` points into the atlas and stays valid until the next call that can
 change the atlas — any call to the glyph lookup, or destroying the atlas.
 The caller uploads it and does not keep it.
 */
typedef struct {
  /*
   The texels, one byte each, row-major from the top, no row padding.
   */
  const uint8_t *bayt;
  /*
   How many bytes, which is width times height.
   */
  size_t tul;
  /*
   Width in texels.
   */
  uint16_t ard;
  /*
   Height in texels.
   */
  uint16_t irtifa;
  /*
   0 for coverage, 1 for a signed distance field.
   */
  uint32_t namat;
} TaaribSafha;

/*
 What the atlas has been doing.
 */
typedef struct {
  /*
   Glyphs served without rasterizing anything.
   */
  uint64_t isabat;
  /*
   Glyphs that had to be rasterized and packed. A number that keeps climbing
   after the first minutes of play means the patch compiler missed strings.
   */
  uint64_t ikhfaqat;
  /*
   Rectangles reclaimed to make room.
   */
  uint64_t ikhlaat;
  /*
   Pages opened after the first.
   */
  uint64_t ahdath_namu;
  /*
   What the pages currently cost, in bytes.
   */
  uint64_t bayt;
  /*
   The byte budget.
   */
  uint64_t mizaniya;
  /*
   How many glyphs are mapped.
   */
  uint32_t ashkal;
  /*
   How many pages are open.
   */
  uint32_t safahat;
} TaaribIhsaatLawha;

/*
 The sink [`taarib_iltiqat_shaghghil`] registers for runtime string capture:
 [`TaaribRaddIltiqat`], made optional so that the null function pointer is
 representable and refused rather than called.

 The sink is invoked as `radd(mustakhdim, nass, tul)`: the registered opaque
 pointer first, then the UTF-8 text of a layout request — `tul` bytes, not
 NUL-terminated, borrowed for the duration of the invocation only, so a sink
 that wants the text copies it before returning.

 It runs on whichever thread called [`taarib_takhtit`], while that context's
 lock is held — which is what makes capture free to leave on, and which is
 why the sink's contract has two halves the host must keep: return promptly,
 because a frame is waiting, and never call back into this library on any
 handle, because the lock it would need is the lock it is running under.

 The signature is written out here rather than as `Option<TaaribRaddIltiqat>`
 for one concrete reason: cbindgen only recognises `Option<T>` as a nullable
 pointer when `T` is a *literal* pointer or function-pointer type, not when it
 is a path alias. Written the short way, the generated header gets an opaque
 `struct Option_TaaribRaddIltiqat` passed by value and no function-pointer
 type at all — a declaration that compiles and cannot be called, which is the
 worst kind of ABI defect because the compiler is satisfied and the consumer
 is stuck. It stays byte-identical to [`TaaribRaddIltiqat`]; keep them so.
 */
typedef void (*TaaribIltiqatFn)(void *mustakhdim, const uint8_t *nass, size_t tul);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Writes the ABI version this library was built as.

 The first call every consumer makes, before creating anything: a caller
 whose compiled-in [`TAARIB_ABI_KABIR`] differs from what this writes must
 refuse to load and say so, because past a major mismatch the two sides no
 longer agree what any structure means. A minor difference is compatible in
 both directions.

 The caller owns both integers; this function only writes them, and nothing
 about them is retained past the call.

 # Safety

 `kabir` and `sagheer` must each be either null or valid for an aligned
 write of one `u32`. Both null is the one degenerate call that has no
 observable effect beyond its status.
 */
int32_t taarib_abi_isdar(uint32_t *kabir, uint32_t *sagheer);

/*
 Writes the library's own release version — the crate version, in semantic
 `major.minor.patch` form — as UTF-8 text with a trailing NUL, for a
 diagnostics screen or a log line.

 The ABI contract is [`taarib_abi_isdar`]; this string is for humans and
 nothing may branch on it.

 The caller owns `hadaf` and its lifetime; nothing is allocated and no
 pointer is retained. When the buffer is too small, `matlub` receives the
 required capacity in bytes (including the NUL), nothing is written, and the
 call returns `TAARIB_SIAT_QASIRA` — grow once and retry.

 # Safety

 `hadaf` must be null or valid for writes of `siaa` bytes, and `matlub` must
 be null or valid for an aligned write of one `usize`.
 */
int32_t taarib_isdar_nass(uint8_t *hadaf, size_t siaa, size_t *matlub);

/*
 The status code of this thread's most recent failure, or zero when the last
 call on this thread succeeded.

 An observer: it reads the thread-local stash and disturbs nothing, so it
 can be called any number of times and interleaved freely with the other
 `taarib_khata_*` functions. The stash is per thread — a failure on the
 render thread is never reported to a loader thread — and it is replaced by
 the next completed call on the same thread, so read it before calling
 anything else.

 # Safety

 None beyond being called at all: the function takes nothing and writes
 through nothing.
 */
int32_t taarib_khata_akhir(void);

/*
 Writes the permanent machine code of this thread's last failure — the
 `TAARIB-E-2503` form that names one specific defect forever — as UTF-8 with
 a trailing NUL.

 Writes an empty string when the last failure carried no structured error (a
 null pointer, a stale handle, a caught panic) or when there was no failure
 at all.

 The caller owns `hadaf`; on `TAARIB_SIAT_QASIRA` the required capacity is
 in `matlub` and nothing was written. An observer: the stashed failure
 survives this call unchanged, including a failed capacity negotiation, so
 probing with a null-size call and retrying cannot erase what it is probing
 for.

 # Safety

 `hadaf` must be null or valid for writes of `siaa` bytes, and `matlub` must
 be null or valid for an aligned write of one `usize`.
 */
int32_t taarib_khata_ramz(uint8_t *hadaf, size_t siaa, size_t *matlub);

/*
 Writes the user-facing sentence of this thread's last failure, as UTF-8
 with a trailing NUL, in the requested language: `0` Arabic, `1` English,
 anything unrecognised Arabic.

 Arabic is the primary text of this product, and a caller that passed a wrong
 number gets the real sentence rather than nothing. Writes an empty string
 when the last failure carried no structured error or there was none.

 The caller owns `hadaf`; on `TAARIB_SIAT_QASIRA` the required capacity is
 in `matlub` and nothing was written. An observer: the stashed failure
 survives this call unchanged, whatever the negotiation returned.

 # Safety

 `hadaf` must be null or valid for writes of `siaa` bytes, and `matlub` must
 be null or valid for an aligned write of one `usize`.
 */
int32_t taarib_khata_nass(uint32_t lugha, uint8_t *hadaf, size_t siaa, size_t *matlub);

/*
 The suggested next action of this thread's last failure, as the stable
 discriminant documented in `docs/abi.md`: `0` nothing, `1` retry, `5` pick
 another font, and so on.

 `0` also when there is no stashed failure. A caller that meets a number it
 does not recognise shows the sentence without a button rather than showing
 nothing — the space is additive.

 An observer: it disturbs nothing.

 # Safety

 None beyond being called at all: the function takes nothing and writes
 through nothing.
 */
int32_t taarib_khata_khutwa(void);

/*
 Creates an engine context: the shaping caches, the layout cache, the pooled
 layout buffers, the handle tables and the capture channel, behind one
 opaque handle.

 `khiyarat` is read once and may be freed the moment this returns; null
 means the defaults, and a non-zero value in the reserved `hashw` field is
 refused with a stashed sentence naming it, so the field stays genuinely
 reserved. This library allocates the context and owns it until
 [`taarib_siyaq_ihdham`] destroys it; the handle written to `khuruj` is
 valid until then and on any thread, one call at a time — calls on the same
 context serialise on an internal lock, so two threads sharing one context
 are safe and slow, and a render thread that wants neither shares nothing.

 # Safety

 `khiyarat` must be null or valid for an aligned read of one
 [`TaaribKhiyaratSiyaq`]; `khuruj` must be valid for an aligned write of one
 pointer.
 */
int32_t taarib_siyaq_insha(const TaaribKhiyaratSiyaq *khiyarat, TaaribSiyaq *khuruj);

/*
 Destroys a context and everything it owns: every font, chain and atlas
 handle issued from it, the layout cache, and the pooled buffers.

 The handle, and every handle issued from it, is dead when this returns; the
 generation tag means a later use is reported as `TAARIB_MAQBAD_BATIL`
 rather than executed. Any page pointer previously borrowed through
 [`taarib_lawha_safha`] dangles from this moment. Destroying a context while
 another thread is inside a call on it waits for that call to finish first,
 which is the lock doing its job.

 # Safety

 `siyaq` must be a handle from [`taarib_siyaq_insha`], or null (refused, not
 dereferenced). No other thread may be *about to* use the handle: the caller
 is responsible for the ordinary teardown ordering of its own threads.
 */
int32_t taarib_siyaq_ihdham(TaaribSiyaq siyaq);

/*
 Empties a context's caches — the layout cache, the pooled layout buffers
 and the prepared shaper state — and returns the memory, without touching a
 single handle.

 For a scene transition or a memory warning: every font, chain and atlas
 handle stays valid, and the only cost of having called this is that the
 next layouts shape again and refill what was dropped.

 # Safety

 `siyaq` must be a live handle from [`taarib_siyaq_insha`], or null
 (refused, not dereferenced).
 */
int32_t taarib_siyaq_amsah(TaaribSiyaq siyaq);

/*
 Loads a font from bytes in the caller's memory and validates it.

 The bytes are **copied**: the caller's buffer is read during this call only
 and may be freed the moment it returns, and the copy becomes the one shared
 buffer that shaping, metrics and rasterization all borrow (Decision 4).
 `fahras` is the face index inside a `ttc`/`otc` collection, `0` for an
 ordinary file. `fahs_arabi` non-zero runs the full Arabic validation of
 Decision 6 — required tables, required features, required coverage — and a
 failure is `TAARIB_KHATT_MARFUD` with a stashed sentence naming the one
 missing thing; zero skips only the Arabic check, for the Latin and
 monospace faces at the end of a chain that will never shape an Arabic
 letter.

 The handle written to `khuruj` belongs to the context and is destroyed by
 [`taarib_khatt_ihdham`] or with the context. Chains hold their own
 references, so destroying the handle after building a chain from it is
 legal and frees nothing until the chain goes too.

 # Safety

 `bayt` must be valid for reads of `tul` bytes; `khuruj` must be valid for
 an aligned write of one pointer; `siyaq` must be a live handle or null
 (refused, not dereferenced).
 */
int32_t taarib_khatt_min_dhakira(TaaribSiyaq siyaq,
                                 const uint8_t *bayt,
                                 size_t tul,
                                 uint32_t fahras,
                                 uint32_t fahs_arabi,
                                 TaaribKhatt *khuruj);

/*
 Destroys a font handle.

 Only the handle dies. A chain built from the font holds its own reference,
 so every chain, every cached layout and every atlas entry that came from
 this font keeps working; the font's bytes are freed when the last of those
 references goes. Destroying an already-destroyed handle is reported as
 `TAARIB_MAQBAD_BATIL`, not executed.

 # Safety

 `siyaq` must be a live handle or null (refused, not dereferenced); `khatt`
 must be a handle this context issued, or null (refused).
 */
int32_t taarib_khatt_ihdham(TaaribSiyaq siyaq, TaaribKhatt khatt);

/*
 Writes a font's own metrics scaled to `hajm` pixels: ascent, descent, line
 gap, recommended line height, cap height, x-height, and the design units
 they were derived at.

 Every value comes from the font's tables or, where a table is silent, from
 measured outline bounds — never from a fraction of the size. `hajm` must be
 finite; beyond that it is taken as given, because a metrics query at an
 unusual size is a legitimate thing for a workspace to ask. The caller owns
 `khuruj`; nothing is retained.

 # Safety

 `khuruj` must be valid for an aligned write of one [`TaaribQiyasatKhatt`];
 `siyaq` and `khatt` must be live handles or null (refused, not
 dereferenced).
 */
int32_t taarib_khatt_qiyasat(TaaribSiyaq siyaq,
                             TaaribKhatt khatt,
                             float hajm,
                             TaaribQiyasatKhatt *khuruj);

/*
 Writes a font's identity: the value derived from its bytes and face index
 that the layout cache and every atlas key are built on.

 Process-local by design — the hash mixes at pointer width — so it may be
 compared, mapped and logged inside this process and must never be persisted
 or sent anywhere. Two handles loaded from identical bytes report the same
 identity, which is exactly what makes the cache key honest.

 # Safety

 `khuruj` must be valid for an aligned write of one `u64`; `siyaq` and
 `khatt` must be live handles or null (refused, not dereferenced).
 */
int32_t taarib_khatt_huwiya(TaaribSiyaq siyaq, TaaribKhatt khatt, uint64_t *khuruj);

/*
 Writes a font's family name — the typographic family where the font
 declares one — as UTF-8 with a trailing NUL, for the workspace's font
 picker and for diagnostics.

 An empty string when the font's `name` table carries neither form, which is
 a broken table and not a reason to refuse the font.

 The caller owns `hadaf`; on `TAARIB_SIAT_QASIRA` the required capacity is
 in `matlub` and nothing was written — grow once and retry.

 # Safety

 `hadaf` must be null or valid for writes of `siaa` bytes; `matlub` must be
 null or valid for an aligned write of one `usize`; `siyaq` and `khatt` must
 be live handles or null (refused, not dereferenced).
 */
int32_t taarib_khatt_aila(TaaribSiyaq siyaq,
                          TaaribKhatt khatt,
                          uint8_t *hadaf,
                          size_t siaa,
                          size_t *matlub);

/*
 Builds a font chain — the ordered list tried per character — from font
 handles, and writes its handle.

 The chain takes its own reference to every font, so the font handles may be
 destroyed afterwards and the chain keeps working. `khutut` is read during
 this call only. An empty chain is refused with a stashed sentence (there
 would be nothing to draw with), a chain longer than 256 likewise (a
 positioned glyph names its font in one byte), and a null or stale handle
 anywhere in the list refuses the whole chain — a chain with a hole in it
 would surface much later as missing glyphs.

 Destroy with [`taarib_silsila_ihdham`] or with the context.

 # Safety

 `khutut` must be valid for reads of `adad` handles; `khuruj` must be valid
 for an aligned write of one pointer; `siyaq` must be a live handle or null
 (refused, not dereferenced).
 */
int32_t taarib_silsila_insha(TaaribSiyaq siyaq,
                             const TaaribKhatt *khutut,
                             size_t adad,
                             TaaribSilsila *khuruj);

/*
 Destroys a chain handle.

 Only the handle dies: the fonts live for as long as anything else
 references them, cached layouts remain valid data, and cache entries keyed
 through this chain simply stop being hit unless an identical chain — same
 fonts, same order — is built again, in which case they hit again, because
 the key names font identities rather than this handle.

 # Safety

 `siyaq` must be a live handle or null (refused, not dereferenced);
 `silsila` must be a handle this context issued, or null (refused).
 */
int32_t taarib_silsila_ihdham(TaaribSiyaq siyaq, TaaribSilsila silsila);

/*
 Lays text out into the caller's buffer. The hot path: a game calls this for
 every visible string, every time one changes.

 The caller owns everything: the request and the text it points at are read
 during this call only, and the glyph and line arrays inside `makhzan` are
 the caller's, written into and never retained, never freed, never
 reallocated. When either array is too small, nothing is written, the
 `adad_*` fields receive the required counts, and the call returns
 `TAARIB_SIAT_QASIRA` — grow once, retry, and the buffer never grows again.

 Allocation: a request already in the layout cache is copied straight out of
 it — the `TAARIB_TAKHTIT_MAKHZAN` flag says so — and the call touches the
 allocator zero times. A request the cache has not seen is shaped into the
 context's pooled buffer and the finished layout is handed to the cache, so
 the next identical request is a hit; the shaping itself is where the work
 and the memory live, and it happens at most once per distinct request.
 There is deliberately no allocating variant of this function.

 When runtime capture is on, a request that missed the cache is reported to
 the registered sink before this returns, whatever the buffer negotiation
 said — new text is new even when the caller's buffer was short. A miss is
 precisely "text this context has not seen", so the stream self-deduplicates
 and steady-state frames report nothing. The sink runs under the context's
 lock and is bound by its registration contract: return promptly, never
 call back into this library.

 # Safety

 `talab` must be valid for an aligned read of one [`TaaribTalab`], and every
 pointer inside it — text, spans, features — must be readable at its stated
 count for the duration of the call. `makhzan` must be valid for an aligned
 read and write of one [`TaaribMakhzanTakhtit`], and its `huruf` and `sutur`
 pointers must be writable at their stated capacities. `siyaq` must be a
 live handle or null (refused, not dereferenced); the chain named by
 `talab.silsila` must belong to the same context.
 */
int32_t taarib_takhtit(TaaribSiyaq siyaq, const TaaribTalab *talab, TaaribMakhzanTakhtit *makhzan);

/*
 Measures text without positioning a single glyph: widest line, total
 height, first ascent, last descent, line count.

 Runs the same policies and the same pipeline as [`taarib_takhtit`], because
 a measurement from any other path would disagree with the layout it
 predicts. A request the layout cache already holds is answered from the
 cached layout without shaping; a request it does not hold is measured
 directly, and — since measurement produces no layout — nothing is inserted,
 so measuring never evicts anything a renderer is relying on.

 The caller owns `talab` and `khuruj`; both are used during this call only.

 # Safety

 `talab` must be valid for an aligned read of one [`TaaribTalab`] with every
 interior pointer readable at its stated count for the duration of the call;
 `khuruj` must be valid for an aligned write of one [`TaaribQiyasNass`];
 `siyaq` must be a live handle or null (refused, not dereferenced); the
 chain named by `talab.silsila` must belong to the same context.
 */
int32_t taarib_qiyas(TaaribSiyaq siyaq, const TaaribTalab *talab, TaaribQiyasNass *khuruj);

/*
 Writes the layout cache's counters: hits, misses, evictions, bytes held,
 the byte budget, and how many layouts are cached.

 Diagnostics, not control: a cache that never hits is a cache whose key is
 wrong, and this is how an adapter's overlay or the Diagnostics screen says
 so with numbers. The caller owns `khuruj`; nothing is retained.

 # Safety

 `khuruj` must be valid for an aligned write of one [`TaaribIhsaatKhazina`];
 `siyaq` must be a live handle or null (refused, not dereferenced).
 */
int32_t taarib_makhzan_ihsaat(TaaribSiyaq siyaq, TaaribIhsaatKhazina *khuruj);

/*
 Creates a runtime glyph atlas inside a byte budget and writes its handle.

 `aqsa_ard` and `aqsa_irtifa` are the largest page dimensions the atlas may
 open — zero means the default of 4096 — and `hashw` is the gutter around
 every glyph in pixels, taken exactly as given, because zero is a meaningful
 (if unwise) choice. `namat` is `0` for coverage pages, `1` for signed
 distance fields, anything else coverage. `mizaniya` is the budget in bytes;
 the page count is derived from it, and a budget too small for one page is
 refused now, with a sentence, rather than per glyph forever.

 The atlas belongs to the context. Destroy it with [`taarib_lawha_ihdham`]
 or with the context; the handle is valid until then.

 # Safety

 `khuruj` must be valid for an aligned write of one pointer; `siyaq` must be
 a live handle or null (refused, not dereferenced).
 */
int32_t taarib_lawha_insha(TaaribSiyaq siyaq,
                           uint16_t aqsa_ard,
                           uint16_t aqsa_irtifa,
                           uint16_t hashw,
                           uint32_t namat,
                           size_t mizaniya,
                           TaaribLawha *khuruj);

/*
 Destroys an atlas and frees its pages.

 Every page pointer previously borrowed from this atlas through
 [`taarib_lawha_safha`] dangles from this moment; a texture the caller
 already uploaded is the caller's and is unaffected. Destroying an
 already-destroyed handle is reported as `TAARIB_MAQBAD_BATIL`, not
 executed.

 # Safety

 `siyaq` must be a live handle or null (refused, not dereferenced); `lawha`
 must be a handle this context issued, or null (refused).
 */
int32_t taarib_lawha_ihdham(TaaribSiyaq siyaq, TaaribLawha lawha);

/*
 Looks a glyph up in the atlas, rasterizing and packing it first if it is
 not there, and writes where it landed and how to draw it.

 The returned position is a value, copied out — the caller may keep it as
 long as it likes, but the *rectangle it names* is guaranteed only for the
 current frame: the glyph is pinned until the next
 [`taarib_lawha_ibda_itar`], and after that the evictor may hand its
 rectangle to another glyph. An adapter that reuses last frame's positions
 re-asks (or re-pins by asking) each frame, which is cheap: a present glyph
 is a hash lookup. The key's font index names a font in `silsila`, which
 must be the chain the layout that produced the glyph id was made with — the
 atlas cannot detect a wrong chain, only a missing font.

 Full-and-unevictable — every rectangle belongs to the frame being drawn —
 is `TAARIB_LAWHA_MUMTALIA` with a sentence naming the pinned count, which
 means the visible text at one instant is larger than the atlas's budget.

 # Safety

 `miftah` must be valid for an aligned read of one [`TaaribMiftahShakl`];
 `khuruj` must be valid for an aligned write of one [`TaaribMawdiShakl`];
 `siyaq`, `lawha` and `silsila` must be live handles or null (refused, not
 dereferenced).
 */
int32_t taarib_lawha_shakl(TaaribSiyaq siyaq,
                           TaaribLawha lawha,
                           TaaribSilsila silsila,
                           const TaaribMiftahShakl *miftah,
                           TaaribMawdiShakl *khuruj);

/*
 Writes a **borrowed** view of one texture page: a pointer into the atlas's
 own memory, its length, its dimensions, and what its bytes mean.

 This is the one function in the surface that hands out a pointer this
 library owns, so its contract is exact. The caller does not free
 `bayt` and does not keep it: it stays valid only until the next call, on
 any thread, that reaches this atlas — [`taarib_lawha_shakl`] may rewrite
 the texels under it, because eviction reuses rectangles, and
 [`taarib_lawha_ihdham`] and [`taarib_siyaq_ihdham`] free the memory under
 it. Read it, upload it, and let it go before touching the context again; a
 caller that wants the bytes longer copies them.

 [`taarib_siyaq_amsah`] is deliberately **not** in that list. It empties the
 shaping caches, the layout cache and the scratch pool, and leaves the font,
 chain and atlas tables exactly as they were — see `Siyaq::amsah`. Saying
 otherwise here would be the conservative direction for this pointer and the
 wrong direction for the page count, where a caller that expected a reset
 would read an unchanged number and report a leak that is not there.

 `fahras` past the last page is `TAARIB_QEEMA_BATILA` — ask
 [`taarib_lawha_adad_safahat`] first, and re-ask after any lookup, because a
 lookup can open a page.

 # Safety

 `khuruj` must be valid for an aligned write of one [`TaaribSafha`];
 `siyaq` and `lawha` must be live handles or null (refused, not
 dereferenced). After this returns, the caller must honour the borrow
 contract above — the library cannot detect a stale page pointer, only
 document when it dies.
 */
int32_t taarib_lawha_safha(TaaribSiyaq siyaq,
                           TaaribLawha lawha,
                           uint16_t fahras,
                           TaaribSafha *khuruj);

/*
 Writes how many pages the atlas currently has open.

 The count only grows within an atlas's life: a lookup can open a page, and
 nothing closes one short of destroying the atlas or its context.
 [`taarib_siyaq_amsah`] does not close pages — it clears the shaping and
 layout caches and leaves the atlas untouched — so an uploader may loop from
 zero to this after its lookups and upload what changed, without having to
 reason about the count going backwards.

 # Safety

 `khuruj` must be valid for an aligned write of one `u32`; `siyaq` and
 `lawha` must be live handles or null (refused, not dereferenced).
 */
int32_t taarib_lawha_adad_safahat(TaaribSiyaq siyaq, TaaribLawha lawha, uint32_t *khuruj);

/*
 Begins a frame on the atlas: releases every glyph the previous frame
 pinned.

 Call once per rendered frame, first thing, from whichever thread renders.
 Every glyph handed out by [`taarib_lawha_shakl`] is pinned against eviction
 until this runs again; an adapter that never calls it fills the atlas with
 unevictable glyphs and then meets `TAARIB_LAWHA_MUMTALIA` — a loud,
 attributable failure rather than a silently wrong letter.

 # Safety

 `siyaq` and `lawha` must be live handles or null (refused, not
 dereferenced).
 */
int32_t taarib_lawha_ibda_itar(TaaribSiyaq siyaq, TaaribLawha lawha);

/*
 Writes the atlas's counters: hits, misses, evictions, growth events, bytes
 held, the byte budget, mapped glyphs and open pages.

 A miss count that keeps climbing after the first minutes of play means the
 patch compiler missed strings, and this is the number the Diagnostics
 screen says it with. The caller owns `khuruj`; nothing is retained.

 # Safety

 `khuruj` must be valid for an aligned write of one [`TaaribIhsaatLawha`];
 `siyaq` and `lawha` must be live handles or null (refused, not
 dereferenced).
 */
int32_t taarib_lawha_ihsaat(TaaribSiyaq siyaq, TaaribLawha lawha, TaaribIhsaatLawha *khuruj);

/*
 Turns runtime string capture on: registers the sink that will receive every
 layout request this context has not seen before.

 From this call until [`taarib_iltiqat_awqif`] or context destruction, a
 [`taarib_takhtit`] that misses the layout cache reports its text to `radd`,
 on the laying-out thread, before the layout call returns. Cache misses are
 precisely "new text", so the stream self-deduplicates and a steady-state
 frame reports nothing, which is what makes this safe to leave on during
 play. The text handed to the sink is borrowed from the layout caller and
 dies when the sink returns; the sink copies what it wants to keep.

 The sink runs while the context's lock is held. That is the registration
 contract, and both halves of it are the host's to keep: the sink returns
 promptly, because a frame is waiting on it, and it never calls back into
 this library on any handle, because the lock it would need is the lock it
 is running under.

 `mustakhdim` is carried through untouched and never dereferenced by this
 library; it must simply stay meaningful to the sink until capture stops. A
 null `radd` is refused — registering nothing is [`taarib_iltiqat_awqif`]'s
 job. Registering again replaces the previous sink atomically with respect
 to layout calls.

 # Safety

 `radd` must be callable under the [`TaaribIltiqatFn`] contract, from any
 thread, and it and `mustakhdim` must remain valid until capture is stopped
 or the context destroyed; `siyaq` must be a live handle or null (refused,
 not dereferenced).
 */
int32_t taarib_iltiqat_shaghghil(TaaribSiyaq siyaq, TaaribIltiqatFn radd, void *mustakhdim);

/*
 Turns runtime string capture off and drops the registered sink.

 Delivery happens under the same context lock this call takes, so when this
 returns the last report has already been delivered: no sink invocation is
 in flight, none will follow, and the sink and its `mustakhdim` may be torn
 down immediately. Stopping capture that was never started succeeds and
 does nothing — the end state is the same.

 # Safety

 `siyaq` must be a live handle or null (refused, not dereferenced).
 */
int32_t taarib_iltiqat_awqif(TaaribSiyaq siyaq);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TAARIB_H */
