//! البوّابة — the gate that proves a package carries no original game asset.
//!
//! This is the product's legal foundation, and the check Phase 18 rejects on. It
//! is therefore not a check.
//!
//! ## Why a check would not be enough
//!
//! A function that walks a finished package looking for game bytes can only
//! ever answer "these bytes do not look like a game asset". It cannot answer
//! "these bytes did not come from a game", because by the time it runs the
//! provenance is gone — a texture read out of `resources.assets` and a texture
//! Taarib rasterized are both a width, a height and a run of bytes.
//!
//! So provenance is carried rather than inferred. [`IthbatTawlid`] is a token
//! that means *Taarib generated these bytes*, it has no public constructor, and
//! the only thing that mints one is [`rassim`] — which takes a glyph set and a
//! chain of Taarib's own bundled fonts, and produces an atlas from them.
//!
//! To get bytes into a package a caller must hold an [`IthbatTawlid`]. To hold
//! one it must have called [`rassim`]. To call [`rassim`] it must have a
//! [`KhattMujammaa`], and a [`KhattMujammaa`] can only name a font inside
//! Taarib's own font directory. There is no path from a game directory to any
//! of those, and adding one would mean adding a constructor in this file — a
//! visible change in a review, rather than a `Vec<u8>` quietly acquiring a new
//! caller somewhere else.
//!
//! ## The difference, not the original
//!
//! Several engines deliver text inside a container that also holds art, audio
//! and code. Rewriting one means producing a file that is mostly the game's own
//! bytes, and shipping that would ship the game.
//!
//! So a package never carries a rewritten container. It carries
//! [`FarqHawiya`] — the instructions to produce one — and Phase 15 applies
//! those to the user's own copy at install time. The original never travels,
//! and the difference is expressed as offsets and replacement text rather than
//! as a byte-level delta against a file this package is not allowed to have
//! read in the first place.
//!
//! ## What this module deliberately does not do
//!
//! It does not scan. There is no entropy heuristic, no signature table, no
//! "does this look like a PNG" test. Every one of those is an inference about
//! bytes whose origin is already known by construction, and adding one would
//! suggest the construction is not trusted — which would be the first step
//! toward relying on the scan instead.

use std::path::{Path, PathBuf};

use taarib_lawha::khareeta::{MawdiShakl, MiftahShakl, NamatSafha};
use taarib_lawha::misafa::KhiyaratMisafa;
use taarib_lawha::{KhiyaratRasf, Lawha};
use taarib_mustalahat::bina::Basma;
use taarib_ruqaa::katib::{KhattMabni, SafhaMabniya, TakhtitMabni};
use taarib_saff::khatt::SilsilatKhutut;

use crate::khata::KhataTarqee;

/// Proof that a run of bytes was generated by Taarib.
///
/// **No public constructor, no public fields, no `Deserialize`.** The last one
/// matters as much as the first two and is the easier to overlook: a
/// `Deserialize` impl is a public constructor, and a token that could be minted
/// out of a JSON object would let a stored package description assert its own
/// provenance. The same reasoning removed `Deserialize` from Phase 13's review
/// attestation.
///
/// Not [`Clone`]. One rasterization produces one atlas page and one proof; a
/// copyable proof would let a single legitimate rasterization escort any number
/// of unrelated byte runs into a package.
#[derive(Debug)]
pub struct IthbatTawlid {
    /// Which fonts produced the bytes, for the record the package carries.
    khutut: Vec<Basma>,
    /// How many glyphs were rasterized, so the manifest can state it.
    ashkal: usize,
}

impl IthbatTawlid {
    /// The fingerprints of the fonts the bytes came out of.
    #[must_use]
    pub fn khutut(&self) -> &[Basma] {
        &self.khutut
    }

    /// How many glyphs the rasterization covered.
    #[must_use]
    pub const fn ashkal(&self) -> usize {
        self.ashkal
    }
}

/// A font Taarib ships, identified and fingerprinted.
///
/// The only thing [`rassim`] will rasterize from. Constructed by
/// [`KhattMujammaa::min_majmua`], which refuses any path that is not inside the
/// font directory — so a caller cannot point it at a `.ttf` sitting in a game's
/// install and call the result bundled.
///
/// Refusing by *location* rather than by a list of known file names is
/// deliberate: a list is something a contributor adds a font to, and the moment
/// it is editable it stops being a boundary.
#[derive(Debug, Clone)]
pub struct KhattMujammaa {
    masar: PathBuf,
    ism: String,
    basma: Basma,
    alam: u16,
}

impl KhattMujammaa {
    /// Accepts a font that lives inside Taarib's own font directory.
    ///
    /// `jidhr_khutut` is [`taarib_usus::masarat::Masarat::khutut`]. The path is
    /// canonicalized before the containment test, because `khutut/../../game/
    /// font.ttf` is inside the directory by string comparison and outside it by
    /// every meaning that matters.
    ///
    /// # Errors
    ///
    /// [`KhataTarqee::KhattKharijMajmua`] when the font is not inside the
    /// directory, and [`KhataTarqee::KhataMalaf`] when it cannot be read to be
    /// fingerprinted.
    pub fn min_majmua(jidhr_khutut: &Path, masar: &Path, alam: u16) -> Result<Self, KhataTarqee> {
        let jidhr = jidhr_khutut
            .canonicalize()
            .map_err(|sabab| KhataTarqee::KhataMalaf {
                masar: jidhr_khutut.to_path_buf(),
                sabab,
            })?;
        let kamil = masar
            .canonicalize()
            .map_err(|sabab| KhataTarqee::KhataMalaf {
                masar: masar.to_path_buf(),
                sabab,
            })?;
        if !kamil.starts_with(&jidhr) {
            return Err(KhataTarqee::KhattKharijMajmua {
                masar: kamil,
                jidhr,
            });
        }

        let bayt = std::fs::read(&kamil).map_err(|sabab| KhataTarqee::KhataMalaf {
            masar: kamil.clone(),
            sabab,
        })?;
        let ism = kamil
            .file_name()
            .and_then(|juz| juz.to_str())
            .unwrap_or("khatt.ttf")
            .to_owned();
        let basma = Basma::min_bayt(*blake3::hash(&bayt).as_bytes());

        Ok(Self {
            masar: kamil,
            ism,
            basma,
            alam,
        })
    }

    /// The font's file name, as the installer will place it.
    #[must_use]
    pub fn ism(&self) -> &str {
        &self.ism
    }

    /// Its content fingerprint.
    #[must_use]
    pub const fn basma(&self) -> Basma {
        self.basma
    }

    /// Where it is on this machine.
    #[must_use]
    pub fn masar(&self) -> &Path {
        &self.masar
    }

    /// The record a package carries about it.
    ///
    /// A name, a hash and a flag — **never the font's bytes**. A package does
    /// not ship the font: the framework does, once, and the hash is what proves
    /// the one on disk at install time is the one this patch was built against.
    #[must_use]
    pub fn sijill(&self) -> KhattMabni {
        KhattMabni {
            ism: self.ism.clone(),
            basma: *self.basma.bayt(),
            alam: self.alam,
        }
    }
}

/// Rasterizes a glyph set and mints the proof that the result was generated.
///
/// **The only source of [`IthbatTawlid`] in this product.**
///
/// Every argument is either a set of glyph keys — which came from shaping the
/// project's own translations — or a chain of fonts each of which passed
/// [`KhattMujammaa::min_majmua`]. There is no parameter through which a byte
/// from a game directory could arrive, which is what makes the guarantee
/// structural rather than asserted.
///
/// # Errors
///
/// [`KhataTarqee::RasfFashil`] when the atlas cannot be built — a glyph set
/// larger than the page budget, a font that will not rasterize — carrying what
/// the atlas pipeline said.
pub fn rassim(
    ashkal: &[MiftahShakl],
    khutut: &[KhattMujammaa],
    silsila: &SilsilatKhutut,
    khiyarat: KhiyaratRasf,
    namat: NamatSafha,
) -> Result<(Lawha, IthbatTawlid), KhataTarqee> {
    let misafa = KhiyaratMisafa::default();
    let lawha = Lawha::ibni(ashkal, silsila, khiyarat, misafa, namat).map_err(|khata| {
        KhataTarqee::RasfFashil {
            sabab: khata.injilizi,
        }
    })?;

    let ithbat = IthbatTawlid {
        khutut: khutut.iter().map(KhattMujammaa::basma).collect(),
        ashkal: ashkal.len(),
    };
    Ok((lawha, ithbat))
}

/// An atlas page that is permitted in a package.
///
/// Wraps the page and consumes the proof. The proof is taken **by value**, so a
/// single rasterization escorts a single batch of pages and cannot be reused —
/// see [`SafhatMasmuha::min_lawha`], which is the only constructor and which
/// takes the whole atlas at once for exactly that reason.
#[derive(Debug)]
pub struct SafhatMasmuha {
    safahat: Vec<SafhaMabniya>,
    khareeta: Vec<(MiftahShakl, MawdiShakl)>,
    ithbat: IthbatTawlid,
}

impl SafhatMasmuha {
    /// Takes every page of a rasterized atlas, with its proof.
    ///
    /// The whole atlas rather than one page, because the proof is not
    /// [`Clone`] and one rasterization legitimately produces several pages. A
    /// per-page constructor would have forced the proof to be copyable, which
    /// is the property that would let it escort bytes it never covered.
    ///
    /// The glyph map travels with the pages rather than beside them. A
    /// rectangle into a page is meaningless without the page and dangerous
    /// with the wrong one: a map paired with an atlas it was not packed against
    /// draws a patch where every glyph is a slice of the glyph next to it. They
    /// are one artefact of one rasterization and there is no constructor that
    /// separates them.
    #[must_use]
    pub fn min_lawha(lawha: &Lawha, ithbat: IthbatTawlid) -> Self {
        let safahat = lawha
            .safahat
            .iter()
            .map(|safha| SafhaMabniya {
                ard: safha.ard,
                irtifa: safha.irtifa,
                bayt: safha.bayt.clone(),
            })
            .collect();
        Self {
            safahat,
            khareeta: lawha.khareeta.murattaba(),
            ithbat,
        }
    }

    /// The pages, for the writer.
    #[must_use]
    pub fn safahat(&self) -> &[SafhaMabniya] {
        &self.safahat
    }

    /// Where every glyph sits, in the key order the container stores.
    #[must_use]
    pub fn khareeta(&self) -> &[(MiftahShakl, MawdiShakl)] {
        &self.khareeta
    }

    /// The proof they came with.
    #[must_use]
    pub const fn ithbat(&self) -> &IthbatTawlid {
        &self.ithbat
    }

    /// Takes the pages, the map and the proof apart, for the writer.
    ///
    /// Consuming rather than borrowing because an atlas is measured in
    /// megabytes and `taarib_ruqaa::katib::Katib::safha` takes a page by value.
    /// Cloning to satisfy that signature would double the peak memory of a
    /// compile for no reason other than an accessor's shape.
    ///
    /// Handing the proof back does not weaken anything. It was never possible
    /// to *make* one, and that is the property the gate rests on; where it
    /// goes afterwards was never the question. It goes into
    /// [`MuhtawaMasmuh::Safahat`], which is what the certificate counts.
    #[must_use]
    pub fn ikhrij(
        self,
    ) -> (
        Vec<SafhaMabniya>,
        Vec<(MiftahShakl, MawdiShakl)>,
        IthbatTawlid,
    ) {
        (self.safahat, self.khareeta, self.ithbat)
    }
}

/// One instruction for producing a patched container at install time.
///
/// The alternative to shipping a rewritten container, and the reason a package
/// bound to an engine that mixes text with art is still legal to distribute.
///
/// Expressed as *where* and *what to put there*, never as a byte-level delta.
/// A delta is computed against the original, which means the machine computing
/// it had the original in memory and the result encodes parts of it — and a
/// package carrying that would be carrying the game, in a form that is harder
/// to notice rather than absent.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct FarqHawiya {
    /// The container, relative to the game's root.
    pub hawiya: String,
    /// The structural location inside it, in the engine's own terms — the same
    /// location Phase 12's table recorded, so an installer resolves it the way
    /// the extractor found it rather than by an offset that a store update
    /// moves.
    pub mawqi: String,
    /// The replacement text.
    pub badil: String,
    /// What the original was, as a fingerprint rather than as text.
    ///
    /// Enough to prove the installer is replacing what the compiler saw, and
    /// **not** enough to reconstruct the original — which is the point. A
    /// package that carried the source text of every string it replaces would
    /// carry the game's script.
    pub basmat_asl: Basma,
}

/// Everything a package is allowed to contain.
///
/// The single type the assembler accepts. Each variant either originates in the
/// project — text the contributor wrote, layouts computed from it — or carries a
/// proof that Taarib generated it.
///
/// There is deliberately **no** variant holding an unattributed `Vec<u8>`. That
/// absence is the guarantee: a future edit wanting to put a game file into a
/// package has to add a variant here, in the file whose entire subject is why
/// that must not happen.
#[derive(Debug)]
pub enum MuhtawaMasmuh {
    /// A source string and its translation, from the project.
    Nass {
        /// The original, which the installer matches against.
        asl: String,
        /// The Arabic.
        tarjama: String,
    },
    /// A layout computed by Phase 1 from a translation.
    Takhtit(TakhtitMabni),
    /// Atlas pages rasterized from bundled fonts, with their proof.
    Safahat(SafhatMasmuha),
    /// A bundled font, by name and hash. Never its bytes.
    Khatt(KhattMabni),
    /// An instruction for producing a patched container at install time.
    Farq(FarqHawiya),
}

impl MuhtawaMasmuh {
    /// Whether this content carries generated bytes, and the proof if so.
    ///
    /// What the package manifest reads to record which fonts a patch was built
    /// from — a fact a reviewer checks and an installer verifies against the
    /// framework's own fonts.
    #[must_use]
    pub const fn ithbat(&self) -> Option<&IthbatTawlid> {
        match self {
            Self::Safahat(safahat) => Some(safahat.ithbat()),
            _ => None,
        }
    }

    /// The name this kind of content carries in the gate's report.
    #[must_use]
    pub const fn naw(&self) -> &'static str {
        match self {
            Self::Nass { .. } => "translated string",
            Self::Takhtit(_) => "precomputed layout",
            Self::Safahat(_) => "glyph atlas",
            Self::Khatt(_) => "bundled font reference",
            Self::Farq(_) => "container difference",
        }
    }
}

/// What the gate certifies about a finished package.
///
/// Written into the package so a reviewer reads it without re-deriving it, and
/// so Phase 18's automated check has a claim to verify rather than a file to
/// guess about.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ShahadatBawwaba {
    /// How many translated strings.
    pub nusus: usize,
    /// How many precomputed layouts.
    pub takhtitat: usize,
    /// How many atlas pages, and the fonts they came from.
    pub safahat: usize,
    /// The fingerprints of every font that produced a page.
    pub khutut: Vec<Basma>,
    /// How many container differences.
    pub furuq: usize,
    /// How many bytes of original game asset the package contains.
    ///
    /// **Always zero, and stated rather than implied.** A reviewer reading a
    /// certificate wants the number, and a field that is structurally incapable
    /// of being anything else is a stronger statement than its absence.
    pub bayt_min_alluba: u64,
}

impl ShahadatBawwaba {
    /// Certifies a set of permitted content.
    ///
    /// Counts rather than inspects. Every item reaching here already proved its
    /// own origin by being a [`MuhtawaMasmuh`]; re-examining the bytes would be
    /// the scan this module's header explains it does not perform.
    #[must_use]
    pub fn min_muhtawa(muhtawa: &[MuhtawaMasmuh]) -> Self {
        let mut shahada = Self {
            nusus: 0,
            takhtitat: 0,
            safahat: 0,
            khutut: Vec::new(),
            furuq: 0,
            bayt_min_alluba: 0,
        };
        for wahid in muhtawa {
            match wahid {
                MuhtawaMasmuh::Nass { .. } => shahada.nusus = shahada.nusus.saturating_add(1),
                MuhtawaMasmuh::Takhtit(_) => {
                    shahada.takhtitat = shahada.takhtitat.saturating_add(1);
                },
                MuhtawaMasmuh::Safahat(safahat) => {
                    shahada.safahat = shahada.safahat.saturating_add(safahat.safahat().len());
                    for basma in safahat.ithbat().khutut() {
                        if !shahada.khutut.contains(basma) {
                            shahada.khutut.push(*basma);
                        }
                    }
                },
                MuhtawaMasmuh::Khatt(_) => {},
                MuhtawaMasmuh::Farq(_) => shahada.furuq = shahada.furuq.saturating_add(1),
            }
        }
        shahada
    }

    /// The sentence the review screen and the package listing show.
    #[must_use]
    pub fn wasf(&self) -> String {
        format!(
            "{} translated string(s), {} precomputed layout(s), {} atlas page(s) rasterized \
             from {} bundled font(s), {} container difference(s), and {} bytes of original \
             game content",
            self.nusus,
            self.takhtitat,
            self.safahat,
            self.khutut.len(),
            self.furuq,
            self.bayt_min_alluba
        )
    }
}
