/**
 * الرقع الخارجية — the vocabulary for a patch somebody else made.
 *
 * Most finished Arabic translations are for engines Taarib has no adapter for,
 * and they work by replacing the game's own files rather than by being
 * compiled into a `.ruqaa`. Taarib cannot build one of those, but it can list
 * it, fetch it against a pinned hash and record the install so it can be
 * undone — so a user gets one experience instead of two.
 *
 * ## Why these types are written here and not read out of `awamir.ts`
 *
 * `awamir.ts` beside this file is generated by `tauri-specta` on every debug
 * build, and it only carries a type once a registered command mentions it. The
 * Rust definitions these mirror — `RuqaaKharijiya`, `QitaatTanzeel`,
 * `TakhtitKhariji`, `TahdheerKhariji`, `HalatMira` in
 * `crates/taarib-mustalahat/src/`, and the commands that answer with them — are
 * being written in parallel with this screen. Until they reach the command
 * surface there is nothing to generate, so the shapes are stated here, field
 * for field, against the agreed contract.
 *
 * When they do land, this file is deleted and the imports move to `awamir.ts`;
 * {@link qarrirKharijiya} below is what makes that safe to do in one step,
 * because every payload is validated against this shape before a screen reads
 * it, so a field that drifted in Rust shows up as a refused answer rather than
 * as `undefined` rendered into a sentence.
 *
 * `RukhsaRuqaa` and `IdhnMasdar` do exist in Rust already — `ruqaa.rs` — but no
 * registered command mentions either yet, so neither is in the bindings. The
 * two restated below carry the wire shapes their serde attributes actually
 * produce: `RukhsaRuqaa` is internally tagged on `naw`, and `IdhnMasdar` is
 * externally tagged, so its two unit cases arrive as bare strings.
 */

/** The licence the work was offered under, as `#[serde(tag = "naw")]` writes it. */
export type RukhsaRuqaa =
  | { readonly naw: 'cc0' }
  | { readonly naw: 'cc_by' }
  | { readonly naw: 'cc_by_sa' }
  | { readonly naw: 'milkiya_khassa' }
  | { readonly naw: 'ukhra'; readonly ism: string };

/** What establishes a right to redistribute somebody else's translation. */
export type IdhnMasdar =
  /** The licence it was published under grants it. */
  | 'rukhsa'
  /** Nothing establishes it. The default for anything found on the internet. */
  | 'lam_yuthbat'
  /** The author granted it directly, and this is how they said so. */
  | { readonly katabi: { readonly bayan: string } };

/**
 * Who made the work, where it lives, and what permits Taarib to carry it.
 *
 * The same record `MasdarKhariji` already holds for a Taarib patch translated
 * from somebody else's work, plus the mirroring flag: mirroring is off unless
 * the permission statement explicitly covers it.
 */
export interface MasdarKhariji {
  /** Who made it, in their own spelling of their own name. */
  readonly ism: string;
  /** Where it was taken from, so the credit points somewhere. */
  readonly rabt: string;
  /** The licence it was offered under, as the importer read it. */
  readonly rukhsa: RukhsaRuqaa;
  /** What establishes the right to redistribute it. */
  readonly idhn: IdhnMasdar;
  /** Whether the permission record covers mirroring. False unless it says so. */
  readonly yasmah_bilmira: boolean;
}

/** One fetched artifact, pinned by hash. */
export interface QitaatTanzeel {
  readonly ism: string;
  /** The author's own endpoint. Never a mirror by default. */
  readonly rabt: string;
  readonly hajm: number;
  /** Lowercase hex sha256. A mismatch is refused by name, never accepted. */
  readonly sha256: string;
  /** Which game builds need this artifact; empty means all of them. */
  readonly abniya: readonly string[];
}

/** What the install writes and what it must clear first. */
export interface TakhtitKhariji {
  /** Paths, relative to the game root, the artifacts unpack to. */
  readonly yaktub: readonly string[];
  /**
   * Paths the author's instructions say to remove before installing. Every one
   * is backed up before removal and restored byte-identical on uninstall.
   */
  readonly yahdhif: readonly string[];
}

/**
 * One safety sentence shown before install, in both languages.
 *
 * The wording travels from the entry rather than from the interface's own
 * string set, so no screen can soften it and no screen can invent one: RDR2's
 * "story mode only, and Red Dead Online has anti-cheat" is the entry's bytes,
 * and the next entry's warning will be its own.
 */
export interface TahdheerKhariji {
  readonly arabi: string;
  readonly injilizi: string;
}

/** Where the bytes come from. Mirroring is off by default. */
export type HalatMira =
  /** Fetched from the author, always. The default. */
  | { readonly naw: 'min_almuallif' }
  /**
   * Mirrored on the registry. Only reachable when the permission record
   * explicitly covers mirroring and the owner turned it on for this entry.
   */
  | { readonly naw: 'min_alsijill'; readonly rabt: string };

/**
 * Where one entry's build question stands on this machine.
 *
 * Three states, and the third is the one that was missing. An entry pins the
 * game's **own** version — Red Dead Redemption 2 calls its builds 1311, 1436
 * and 1491 — while what Taarib records is what the *launcher* calls the same
 * install: a Steam `buildid`, a GOG hash, or nothing at all. Two numbers
 * written in different vocabularies failing to be equal establishes nothing, so
 * a card that read that as "no file matches this game build" was stating a fact
 * nobody had.
 *
 * `majhula` is not `ghayr_madumma`. "I could not tell" and "I can tell, and no"
 * are different sentences and different decisions: the first has an explicit
 * way past and the second has none.
 */
export type HalatBina =
  /** Determined, and the entry pins files for it. */
  | { readonly naw: 'mutabaqa'; readonly bina: string }
  /** Determined, and the entry does not cover it. A real mismatch. */
  | { readonly naw: 'ghayr_madumma'; readonly bina: string }
  /** Not determined at all. The entry's own builds are what the reader checks. */
  | { readonly naw: 'majhula' };

/** A patch somebody else made, that Taarib lists and installs but never built. */
export interface RuqaaKharijiya {
  readonly id: string;
  readonly unwan: string;
  readonly luba: string;
  /** The game as each launcher names it, so one entry covers Steam/Rockstar/Epic. */
  readonly hawiyat_manassa: readonly string[];
  /** Game builds this patch supports, e.g. `["1311","1436","1491"]`. */
  readonly abniya: readonly string[];
  /** Who made it, where, under what licence, and what permits republishing it. */
  readonly masdar: MasdarKhariji;
  /** The team name, when the work is a team's. */
  readonly fariq: string | null;
  readonly isdar: string;
  /** Everything fetched, each pinned. */
  readonly qitaa: readonly QitaatTanzeel[];
  readonly takhtit: TakhtitKhariji;
  /** Safety sentences shown before install, both languages. */
  readonly tahdheerat: readonly TahdheerKhariji[];
  /** Mirroring is off unless the permission covers it and the owner enabled it. */
  readonly mira: HalatMira;
  /** Where this entry's build question stands on this machine. */
  readonly halat_bina: HalatBina;
  /** Whether this entry is installed into this game right now. */
  readonly muthabbata: boolean;
}

/**
 * What is already in the game directory that this install cannot sit beside.
 *
 * Two loaders cannot both own a slot: RTEA occupies `dinput8.dll`, Taarib's own
 * `mudkhal` occupies `version.dll`, and the author's own instructions tell
 * users to delete the other one. The install refuses in both directions, and a
 * refusal that says only "conflict" is a dead end — so the report names what is
 * there, which slot it holds, and exactly what has to go first.
 */
export interface TadakhulKhariji {
  /** Whether anything conflicting is in the game directory right now. */
  readonly mutadakhil: boolean;
  /** What is already installed, named, in Arabic. */
  readonly sahib_arabi: string;
  /** The same, in English. */
  readonly sahib_injilizi: string;
  /** The loader slot the conflict is over, e.g. `dinput8.dll`. */
  readonly manfadh: string;
  /** Paths, relative to the game root, that must go before this can install. */
  readonly yuzal: readonly string[];
  /**
   * Whether Taarib's own removal can do it.
   *
   * True when what is in the way is Taarib's own install, which the removal
   * strip on this same screen takes off and restores. False when it is another
   * team's, which Taarib did not write and will not delete on its own.
   */
  readonly taarib_yuzil: boolean;
}

/** What an install of a third-party patch actually did. */
export interface NatijatKharijiya {
  /** Whether every fetched artifact matched its pinned hash. */
  readonly basmat_mutabiqa: boolean;
  /** How many paths were written into the game. */
  readonly adad_maktub: number;
  /** How many of the author's listed removals were backed up first. */
  readonly adad_muhtafaz: number;
  /** The record the removal reads back, so the install can be undone. */
  readonly sijill: string;
}

/**
 * An artifact the author has changed since the owner pinned it.
 *
 * The card offers the update; installing it is refused until the owner has
 * looked at the new hash and accepted it deliberately. A compromised author
 * server must not be able to push arbitrary bytes to users on the strength of
 * a version number having moved.
 */
export interface BasmaMualaqa {
  /** The entry the changed artifact belongs to. */
  readonly ruqaa: string;
  readonly unwan: string;
  /** Who made it, for the console row: credit is owed here too. */
  readonly muallif: string;
  readonly fariq: string | null;
  readonly rabt_muallif: string;
  /** The version the author now ships. */
  readonly isdar: string;
  /** The version the standing pin was taken against. */
  readonly isdar_mathbut: string;
  /** Which artifact changed. */
  readonly qitaa: string;
  /** Where it was fetched from. */
  readonly rabt: string;
  /** Bytes, as the author's endpoint reports them now. */
  readonly hajm: number;
  /** Bytes, as the standing pin records them. */
  readonly hajm_mathbut: number;
  /** The hash the owner pinned, lowercase hex. */
  readonly sha256_mathbut: string;
  /** The hash the artifact actually has now, lowercase hex. */
  readonly sha256_marsud: string;
  /** When the change was observed, RFC 3339. */
  readonly waqt: string;
}

/* ===========================================================================
   The decoders.

   Every one of these is total: it answers a value or null, and never throws,
   because it runs on whatever the backend sent rather than on what this build
   expects. A field that drifted in Rust reaches a screen as a refused answer
   with the entry named, not as `undefined` interpolated into a credit line.
   =========================================================================== */

/** A JSON object, as far as a decoder can tell before it reads a field. */
type Kain = Readonly<Record<string, unknown>>;

function kain(qeema: unknown): Kain | null {
  return typeof qeema === 'object' && qeema !== null && !Array.isArray(qeema)
    ? (qeema as Kain)
    : null;
}

function nass(qeema: unknown): string | null {
  return typeof qeema === 'string' ? qeema : null;
}

/** A string that is allowed to be absent, answered as null when it is. */
function nassAw(qeema: unknown): string | null {
  return qeema === null || qeema === undefined ? null : nass(qeema);
}

function raqm(qeema: unknown): number | null {
  return typeof qeema === 'number' && Number.isFinite(qeema) ? qeema : null;
}

function mantiq(qeema: unknown): boolean | null {
  return typeof qeema === 'boolean' ? qeema : null;
}

function qaimatNusus(qeema: unknown): readonly string[] | null {
  if (!Array.isArray(qeema)) {
    return null;
  }
  const kharij: string[] = [];
  for (const wahid of qeema as readonly unknown[]) {
    const matn = nass(wahid);
    if (matn === null) {
      return null;
    }
    kharij.push(matn);
  }
  return kharij;
}

/** A list whose every element decodes, or null the moment one does not. */
function qaima<T>(qeema: unknown, qarrir: (wahid: unknown) => T | null): readonly T[] | null {
  if (!Array.isArray(qeema)) {
    return null;
  }
  const kharij: T[] = [];
  for (const wahid of qeema as readonly unknown[]) {
    const mafkuk = qarrir(wahid);
    if (mafkuk === null) {
      return null;
    }
    kharij.push(mafkuk);
  }
  return kharij;
}

/**
 * The licence, internally tagged on `naw`.
 *
 * Nothing here paraphrases it: the value is handed to the screen exactly as
 * Rust spells the case, so the screen reads the same union it reads off a
 * Taarib patch's own listing and names a recognised licence by its identifier
 * rather than by a sentence somebody wrote twice.
 */
function qarrirRukhsa(qeema: unknown): RukhsaRuqaa | null {
  const kaen = kain(qeema);
  if (kaen === null) {
    return null;
  }
  const naw = nass(kaen['naw']);
  if (naw === 'cc0' || naw === 'cc_by' || naw === 'cc_by_sa' || naw === 'milkiya_khassa') {
    return { naw };
  }
  if (naw !== 'ukhra') {
    return null;
  }
  const ism = nass(kaen['ism']);
  return ism === null ? null : { naw, ism };
}

/** The permission, externally tagged: two unit cases and one record. */
function qarrirIdhn(qeema: unknown): IdhnMasdar | null {
  const matn = nass(qeema);
  if (matn === 'rukhsa' || matn === 'lam_yuthbat') {
    return matn;
  }
  const kaen = kain(qeema);
  const katabi = kaen === null ? null : kain(kaen['katabi']);
  const bayan = katabi === null ? null : nass(katabi['bayan']);
  return bayan === null ? null : { katabi: { bayan } };
}

function qarrirMasdar(qeema: unknown): MasdarKhariji | null {
  const kaen = kain(qeema);
  if (kaen === null) {
    return null;
  }
  const ism = nass(kaen['ism']);
  const rabt = nass(kaen['rabt']);
  const rukhsa = qarrirRukhsa(kaen['rukhsa']);
  const idhn = qarrirIdhn(kaen['idhn']);
  const mira = mantiq(kaen['yasmah_bilmira']);
  if (ism === null || rabt === null || rukhsa === null || idhn === null || mira === null) {
    return null;
  }
  return { ism, rabt, rukhsa, idhn, yasmah_bilmira: mira };
}

function qarrirQitaa(qeema: unknown): QitaatTanzeel | null {
  const kaen = kain(qeema);
  if (kaen === null) {
    return null;
  }
  const ism = nass(kaen['ism']);
  const rabt = nass(kaen['rabt']);
  const hajm = raqm(kaen['hajm']);
  const sha256 = nass(kaen['sha256']);
  const abniya = qaimatNusus(kaen['abniya']);
  if (ism === null || rabt === null || hajm === null || sha256 === null || abniya === null) {
    return null;
  }
  return { ism, rabt, hajm, sha256, abniya };
}

function qarrirTakhtit(qeema: unknown): TakhtitKhariji | null {
  const kaen = kain(qeema);
  if (kaen === null) {
    return null;
  }
  const yaktub = qaimatNusus(kaen['yaktub']);
  const yahdhif = qaimatNusus(kaen['yahdhif']);
  return yaktub === null || yahdhif === null ? null : { yaktub, yahdhif };
}

function qarrirTahdheer(qeema: unknown): TahdheerKhariji | null {
  const kaen = kain(qeema);
  if (kaen === null) {
    return null;
  }
  const arabi = nass(kaen['arabi']);
  const injilizi = nass(kaen['injilizi']);
  return arabi === null || injilizi === null ? null : { arabi, injilizi };
}

/**
 * Where the bytes come from.
 *
 * A bare `"min_almuallif"` is the default and the overwhelming case; the
 * mirrored case is an object carrying the registry address. An answer this
 * build cannot read is **not** defaulted to the author — defaulting it would
 * mean drawing "fetched from the author" over a mirror, which is the one claim
 * this field exists to keep honest — so it refuses the whole entry instead.
 */
function qarrirMira(qeema: unknown): HalatMira | null {
  if (nass(qeema) === 'min_almuallif') {
    return { naw: 'min_almuallif' };
  }
  const kaen = kain(qeema);
  const sijill = kaen === null ? null : kain(kaen['min_alsijill']);
  const rabt = sijill === null ? null : nass(sijill['rabt']);
  return rabt === null ? null : { naw: 'min_alsijill', rabt };
}

/**
 * Where the build question stands, internally tagged on `naw` as Rust writes
 * it.
 *
 * An answer this build cannot read is **not** defaulted to undetermined and is
 * not defaulted to a match: it refuses the whole entry. Each of the three
 * states is a different sentence shown to somebody about to write files into a
 * game, and choosing one of them for a payload nobody could read would be
 * inventing exactly the determination this field exists to stop being invented.
 */
function qarrirHalatBina(qeema: unknown): HalatBina | null {
  const kaen = kain(qeema);
  if (kaen === null) {
    return null;
  }
  const naw = nass(kaen['naw']);
  if (naw === 'majhula') {
    return { naw };
  }
  if (naw !== 'mutabaqa' && naw !== 'ghayr_madumma') {
    return null;
  }
  const bina = nass(kaen['bina']);
  return bina === null ? null : { naw, bina };
}

/** One third-party entry, or null when the payload is not one. */
export function qarrirKharijiya(qeema: unknown): RuqaaKharijiya | null {
  const kaen = kain(qeema);
  if (kaen === null) {
    return null;
  }
  const id = nass(kaen['id']);
  const unwan = nass(kaen['unwan']);
  const luba = nass(kaen['luba']);
  const hawiyat = qaimatNusus(kaen['hawiyat_manassa']);
  const abniya = qaimatNusus(kaen['abniya']);
  const masdar = qarrirMasdar(kaen['masdar']);
  const isdar = nass(kaen['isdar']);
  const qitaa = qaima(kaen['qitaa'], qarrirQitaa);
  const takhtit = qarrirTakhtit(kaen['takhtit']);
  const tahdheerat = qaima(kaen['tahdheerat'], qarrirTahdheer);
  const mira = qarrirMira(kaen['mira']);
  const halatBina = qarrirHalatBina(kaen['halat_bina']);
  const muthabbata = mantiq(kaen['muthabbata']);
  if (
    id === null ||
    unwan === null ||
    luba === null ||
    hawiyat === null ||
    abniya === null ||
    masdar === null ||
    isdar === null ||
    qitaa === null ||
    takhtit === null ||
    tahdheerat === null ||
    mira === null ||
    halatBina === null ||
    muthabbata === null
  ) {
    return null;
  }
  return {
    id,
    unwan,
    luba,
    hawiyat_manassa: hawiyat,
    abniya,
    masdar,
    fariq: nassAw(kaen['fariq']),
    isdar,
    qitaa,
    takhtit,
    tahdheerat,
    mira,
    halat_bina: halatBina,
    muthabbata,
  };
}

/** The whole catalogue for one game, or null when any entry fails to decode. */
export function qarrirKatalog(qeema: unknown): readonly RuqaaKharijiya[] | null {
  return qaima(qeema, qarrirKharijiya);
}

/** The collision report, or null when the payload is not one. */
export function qarrirTadakhul(qeema: unknown): TadakhulKhariji | null {
  const kaen = kain(qeema);
  if (kaen === null) {
    return null;
  }
  const mutadakhil = mantiq(kaen['mutadakhil']);
  const sahibArabi = nass(kaen['sahib_arabi']);
  const sahibInjilizi = nass(kaen['sahib_injilizi']);
  const manfadh = nass(kaen['manfadh']);
  const yuzal = qaimatNusus(kaen['yuzal']);
  const taarib = mantiq(kaen['taarib_yuzil']);
  if (
    mutadakhil === null ||
    sahibArabi === null ||
    sahibInjilizi === null ||
    manfadh === null ||
    yuzal === null ||
    taarib === null
  ) {
    return null;
  }
  return {
    mutadakhil,
    sahib_arabi: sahibArabi,
    sahib_injilizi: sahibInjilizi,
    manfadh,
    yuzal,
    taarib_yuzil: taarib,
  };
}

/** What an install produced, or null when the payload is not that. */
export function qarrirNatija(qeema: unknown): NatijatKharijiya | null {
  const kaen = kain(qeema);
  if (kaen === null) {
    return null;
  }
  const basmat = mantiq(kaen['basmat_mutabiqa']);
  const maktub = raqm(kaen['adad_maktub']);
  const muhtafaz = raqm(kaen['adad_muhtafaz']);
  const sijill = nass(kaen['sijill']);
  if (basmat === null || maktub === null || muhtafaz === null || sijill === null) {
    return null;
  }
  return {
    basmat_mutabiqa: basmat,
    adad_maktub: maktub,
    adad_muhtafaz: muhtafaz,
    sijill,
  };
}

/** One pending re-pin, or null when the payload is not one. */
export function qarrirBasma(qeema: unknown): BasmaMualaqa | null {
  const kaen = kain(qeema);
  if (kaen === null) {
    return null;
  }
  const ruqaa = nass(kaen['ruqaa']);
  const unwan = nass(kaen['unwan']);
  const muallif = nass(kaen['muallif']);
  const rabtMuallif = nass(kaen['rabt_muallif']);
  const isdar = nass(kaen['isdar']);
  const isdarMathbut = nass(kaen['isdar_mathbut']);
  const qitaa = nass(kaen['qitaa']);
  const rabt = nass(kaen['rabt']);
  const hajm = raqm(kaen['hajm']);
  const hajmMathbut = raqm(kaen['hajm_mathbut']);
  const mathbut = nass(kaen['sha256_mathbut']);
  const marsud = nass(kaen['sha256_marsud']);
  const waqt = nass(kaen['waqt']);
  if (
    ruqaa === null ||
    unwan === null ||
    muallif === null ||
    rabtMuallif === null ||
    isdar === null ||
    isdarMathbut === null ||
    qitaa === null ||
    rabt === null ||
    hajm === null ||
    hajmMathbut === null ||
    mathbut === null ||
    marsud === null ||
    waqt === null
  ) {
    return null;
  }
  return {
    ruqaa,
    unwan,
    muallif,
    fariq: nassAw(kaen['fariq']),
    rabt_muallif: rabtMuallif,
    isdar,
    isdar_mathbut: isdarMathbut,
    qitaa,
    rabt,
    hajm,
    hajm_mathbut: hajmMathbut,
    sha256_mathbut: mathbut,
    sha256_marsud: marsud,
    waqt,
  };
}

/** Every pending re-pin, or null when any of them fails to decode. */
export function qarrirBasmat(qeema: unknown): readonly BasmaMualaqa[] | null {
  return qaima(qeema, qarrirBasma);
}

/* ===========================================================================
   Reading an entry.
   =========================================================================== */

/**
 * The artifacts that apply to one build.
 *
 * An artifact with an empty `abniya` applies to every build; one that names
 * builds applies only to those. RTEA is the shape this exists for: `update.zip`
 * is fetched for all three supported builds and `extra.zip` only for two of
 * them, so a screen that showed both to a 1491 player would be overstating what
 * is about to be downloaded by a megabyte and a half.
 */
function qitaaLiBina(madkhal: RuqaaKharijiya, bina: string): readonly QitaatTanzeel[] {
  return madkhal.qitaa.filter((wahid) => wahid.abniya.length === 0 || wahid.abniya.includes(bina));
}

/**
 * Which artifacts this install would fetch, given where the build question
 * stands.
 *
 * Determined and covered selects the artifacts for that build. Determined and
 * *not* covered selects none at all — the entry was never tested against this
 * install, the gate refuses it, and listing the build-agnostic artifacts as
 * though something were about to be downloaded would be describing a transfer
 * that will not happen. Undetermined lists everything, because the honest
 * answer to "which of these apply" is then "we cannot tell, so here is all of
 * it".
 */
export function qitaaLiHala(madkhal: RuqaaKharijiya, hala: HalatBina): readonly QitaatTanzeel[] {
  if (hala.naw === 'mutabaqa') {
    return qitaaLiBina(madkhal, hala.bina);
  }
  return hala.naw === 'ghayr_madumma' ? [] : madkhal.qitaa;
}

/**
 * The builds this entry names, out of the entry's own bytes and nowhere else.
 *
 * Its declared list when it has one, which is the maker's own statement of what
 * the work supports. Otherwise the builds its artifacts are pinned to, in the
 * order they were declared and without repeats — an entry that named no list
 * but pinned `extra.zip` to two builds has still named two builds, and a
 * sentence about which builds it covers cannot be written without them.
 *
 * Never a table, never a constant: a sentence that names 1311, 1436 and 1491
 * names them because this entry does.
 */
export function abniyaMusamma(madkhal: RuqaaKharijiya): readonly string[] {
  if (madkhal.abniya.length > 0) {
    return madkhal.abniya;
  }
  const majmua: string[] = [];
  for (const qitaa of madkhal.qitaa) {
    for (const bina of qitaa.abniya) {
      if (!majmua.includes(bina)) {
        majmua.push(bina);
      }
    }
  }
  return majmua;
}

/**
 * Whether the build question changes anything for this entry at all.
 *
 * True when the entry names any build — its own list, or a build one artifact
 * is pinned to. RTEA's `extra.zip` is 1311 and 1436 alone while `update.zip` is
 * every build, so which build this is decides what gets written. False when
 * nothing in the entry distinguishes one build from another, and then an
 * undetermined build is not a risk anybody has to accept: every file applies
 * whatever this install turns out to be.
 */
export function yufarriqAbniya(madkhal: RuqaaKharijiya): boolean {
  return abniyaMusamma(madkhal).length > 0;
}

/** What the listed artifacts weigh together, in bytes. */
export function hajmQitaa(qitaa: readonly QitaatTanzeel[]): number {
  return qitaa.reduce((majmu, wahid) => majmu + wahid.hajm, 0);
}

/**
 * Whether the entry may be offered at all.
 *
 * A third-party entry whose permission is not a written grant, or whose grant
 * is blank, is refused by the backend's own gate. The interface asks the same
 * question so that it never draws an install button the backend would refuse —
 * a control that cannot do what it says is worse than no control.
 */
export function maadhun(masdar: MasdarKhariji): boolean {
  if (typeof masdar.idhn === 'string') {
    return false;
  }
  return masdar.idhn.katabi.bayan.trim() !== '';
}

/** The eight-character groups a hash is read in, so two of them can be compared. */
export const TUL_MAJMUA = 8;

/** A lowercase hex hash, cut into readable groups. */
export function majmuatBasma(basma: string): readonly string[] {
  const majmuat: string[] = [];
  for (let bidaya = 0; bidaya < basma.length; bidaya += TUL_MAJMUA) {
    majmuat.push(basma.slice(bidaya, bidaya + TUL_MAJMUA));
  }
  return majmuat;
}

/**
 * How many characters of the new hash the owner has to re-enter to accept it.
 *
 * Long enough that it cannot be produced by glancing at the field and long
 * enough to be worth typing deliberately; short enough that it is read off the
 * screen rather than copied blind. The check is exact and case-insensitive
 * only in that the field is lowercased before comparison.
 */
export const TUL_TAAKID_BASMA = 12;

/** The tail of a hash the owner is asked to re-enter. */
export function dhaylBasma(basma: string): string {
  return basma.slice(-TUL_TAAKID_BASMA);
}
